### ISSUE TITLE
Image doesn't build using web Dockerfile

### ISSUE THREAD

**Issue by saltysoup** [kneekey23/NerdDinner#2]
1. Invalid references
2. Step 2/13 : WORKDIR C:\src
the working directory 'C:src' is invalid, it needs to be an absolute path

As per Directions.md
1. Build the web app image
docker image build -t nerd-dinner/web -f web\Dockerfile .

PS C:\docker\NerdDinner-master\NerdDinner-master> docker image build -t nerd-dinner/web -f web\Dockerfile .
Sending build context to Docker daemon 199.5 MB
Step 1/13 : FROM microsoft/dotnet-framework:4.7.2-sdk AS builder
Error parsing reference: "microsoft/dotnet-framework:4.7.2-sdk AS builder" is not a valid repository/tag: invalid reference format

-----------
Environment info using the latest AWS AMI for Windows Server 2016 with containers
(Maybe docker server version is too old and doesn't support format FROM <image> [AS <name>] ??)

C:\Users\Administrator>docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 24
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2430.amd64fre.rs1_release_inmarket_aim.180806-1810)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16 GiB
Name: EC2AMAZ-SOUFROL
ID: VZIV:QABT:63VB:KUOW:4FOR:BTTB:QULZ:U7KS:CIZK:QWTU:63SI:65EG
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

------------

Replacing all backslashes \ with forwardslashes /, and making the directory before setting workdir seems to make it work

# escape=`
FROM microsoft/dotnet-framework:4.7.2-sdk

RUN mkdir C:/src
WORKDIR C:/src
COPY *.sln .
COPY NerdDinner/NerdDinner.csproj ./NerdDinner/
RUN nuget restore

COPY . C:/src
RUN msbuild NerdDinner/NerdDinner.csproj /p:OutputPath=c:/out /p:Configuration=Release

# app image
FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

ENV APP_ROOT=C:/web-app

WORKDIR ${APP_ROOT}
RUN Remove-Website -Name 'Default Web Site';`
    New-Website -Name 'web-app' -Port 80 -PhysicalPath $env:APP_ROOT; `
    New-WebApplication -Name 'app' -Site 'web-app' -PhysicalPath $env:APP_ROOT

#COPY --from=microsoft/dotnet-framework:4.7.2-sdk C:/out/_PublishedWebsites/NerdDinner .

**Comment by kneekey23** [comment]
Hi @saltysoup this docker file is doing a multi stage build which is a new feature requiring Docker 17.05. when you call `docker version`, what version number is listed? I don't see your docker version from your `docker info` call above. in terms of the other issues, windows and docker released patches since i posted this repo so i know there are issues and I will be fixing them and replacing this content shortly. I am so sorry you experienced issues but it seems like you figured them out? Is there anything additional I can help you with in the meantime before I fix these issues?

**Comment by saltysoup** [comment]
Hi Nicole, no big deal I guess the version of docker running in the AWS supplied Windows Server 2016 AMI is a little dated (see below output). Not a huge deal, but thought I'd float this up to you in case you were thinking about running a future workshop or lab.

PS C:\Users\Administrator> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
